// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: calculator/v1/calculator.proto

package v1connect

import (
	v1 "calculator/backend/pkg/protobuf/calculator/v1"
	context "context"
	errors "errors"
	connect_go "github.com/bufbuild/connect-go"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// CalculatorServiceName is the fully-qualified name of the CalculatorService service.
	CalculatorServiceName = "calculator.v1.CalculatorService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// CalculatorServiceCalculateProcedure is the fully-qualified name of the CalculatorService's
	// Calculate RPC.
	CalculatorServiceCalculateProcedure = "/calculator.v1.CalculatorService/Calculate"
	// CalculatorServiceGetHistoryProcedure is the fully-qualified name of the CalculatorService's
	// GetHistory RPC.
	CalculatorServiceGetHistoryProcedure = "/calculator.v1.CalculatorService/GetHistory"
)

// CalculatorServiceClient is a client for the calculator.v1.CalculatorService service.
type CalculatorServiceClient interface {
	Calculate(context.Context, *connect_go.Request[v1.CalculationRequest]) (*connect_go.Response[v1.CalculationResponse], error)
	GetHistory(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.CalculationHistoryResponse], error)
}

// NewCalculatorServiceClient constructs a client for the calculator.v1.CalculatorService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewCalculatorServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) CalculatorServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &calculatorServiceClient{
		calculate: connect_go.NewClient[v1.CalculationRequest, v1.CalculationResponse](
			httpClient,
			baseURL+CalculatorServiceCalculateProcedure,
			opts...,
		),
		getHistory: connect_go.NewClient[emptypb.Empty, v1.CalculationHistoryResponse](
			httpClient,
			baseURL+CalculatorServiceGetHistoryProcedure,
			opts...,
		),
	}
}

// calculatorServiceClient implements CalculatorServiceClient.
type calculatorServiceClient struct {
	calculate  *connect_go.Client[v1.CalculationRequest, v1.CalculationResponse]
	getHistory *connect_go.Client[emptypb.Empty, v1.CalculationHistoryResponse]
}

// Calculate calls calculator.v1.CalculatorService.Calculate.
func (c *calculatorServiceClient) Calculate(ctx context.Context, req *connect_go.Request[v1.CalculationRequest]) (*connect_go.Response[v1.CalculationResponse], error) {
	return c.calculate.CallUnary(ctx, req)
}

// GetHistory calls calculator.v1.CalculatorService.GetHistory.
func (c *calculatorServiceClient) GetHistory(ctx context.Context, req *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.CalculationHistoryResponse], error) {
	return c.getHistory.CallUnary(ctx, req)
}

// CalculatorServiceHandler is an implementation of the calculator.v1.CalculatorService service.
type CalculatorServiceHandler interface {
	Calculate(context.Context, *connect_go.Request[v1.CalculationRequest]) (*connect_go.Response[v1.CalculationResponse], error)
	GetHistory(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.CalculationHistoryResponse], error)
}

// NewCalculatorServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewCalculatorServiceHandler(svc CalculatorServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	calculatorServiceCalculateHandler := connect_go.NewUnaryHandler(
		CalculatorServiceCalculateProcedure,
		svc.Calculate,
		opts...,
	)
	calculatorServiceGetHistoryHandler := connect_go.NewUnaryHandler(
		CalculatorServiceGetHistoryProcedure,
		svc.GetHistory,
		opts...,
	)
	return "/calculator.v1.CalculatorService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case CalculatorServiceCalculateProcedure:
			calculatorServiceCalculateHandler.ServeHTTP(w, r)
		case CalculatorServiceGetHistoryProcedure:
			calculatorServiceGetHistoryHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedCalculatorServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedCalculatorServiceHandler struct{}

func (UnimplementedCalculatorServiceHandler) Calculate(context.Context, *connect_go.Request[v1.CalculationRequest]) (*connect_go.Response[v1.CalculationResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("calculator.v1.CalculatorService.Calculate is not implemented"))
}

func (UnimplementedCalculatorServiceHandler) GetHistory(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.CalculationHistoryResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("calculator.v1.CalculatorService.GetHistory is not implemented"))
}
