// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: calculator/v1/calculator.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CalculationHistoryItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operand1      float64                `protobuf:"fixed64,1,opt,name=operand1,proto3" json:"operand1,omitempty"`
	Operand2      float64                `protobuf:"fixed64,2,opt,name=operand2,proto3" json:"operand2,omitempty"`
	Operator      string                 `protobuf:"bytes,3,opt,name=operator,proto3" json:"operator,omitempty"`
	Result        float64                `protobuf:"fixed64,4,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculationHistoryItem) Reset() {
	*x = CalculationHistoryItem{}
	mi := &file_calculator_v1_calculator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculationHistoryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculationHistoryItem) ProtoMessage() {}

func (x *CalculationHistoryItem) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_v1_calculator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculationHistoryItem.ProtoReflect.Descriptor instead.
func (*CalculationHistoryItem) Descriptor() ([]byte, []int) {
	return file_calculator_v1_calculator_proto_rawDescGZIP(), []int{0}
}

func (x *CalculationHistoryItem) GetOperand1() float64 {
	if x != nil {
		return x.Operand1
	}
	return 0
}

func (x *CalculationHistoryItem) GetOperand2() float64 {
	if x != nil {
		return x.Operand2
	}
	return 0
}

func (x *CalculationHistoryItem) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *CalculationHistoryItem) GetResult() float64 {
	if x != nil {
		return x.Result
	}
	return 0
}

type CalculationHistoryResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Items         []*CalculationHistoryItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculationHistoryResponse) Reset() {
	*x = CalculationHistoryResponse{}
	mi := &file_calculator_v1_calculator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculationHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculationHistoryResponse) ProtoMessage() {}

func (x *CalculationHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_v1_calculator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculationHistoryResponse.ProtoReflect.Descriptor instead.
func (*CalculationHistoryResponse) Descriptor() ([]byte, []int) {
	return file_calculator_v1_calculator_proto_rawDescGZIP(), []int{1}
}

func (x *CalculationHistoryResponse) GetItems() []*CalculationHistoryItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type CalculationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operand1      float64                `protobuf:"fixed64,1,opt,name=operand1,proto3" json:"operand1,omitempty"`
	Operand2      float64                `protobuf:"fixed64,2,opt,name=operand2,proto3" json:"operand2,omitempty"`
	Operator      string                 `protobuf:"bytes,3,opt,name=operator,proto3" json:"operator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculationRequest) Reset() {
	*x = CalculationRequest{}
	mi := &file_calculator_v1_calculator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculationRequest) ProtoMessage() {}

func (x *CalculationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_v1_calculator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculationRequest.ProtoReflect.Descriptor instead.
func (*CalculationRequest) Descriptor() ([]byte, []int) {
	return file_calculator_v1_calculator_proto_rawDescGZIP(), []int{2}
}

func (x *CalculationRequest) GetOperand1() float64 {
	if x != nil {
		return x.Operand1
	}
	return 0
}

func (x *CalculationRequest) GetOperand2() float64 {
	if x != nil {
		return x.Operand2
	}
	return 0
}

func (x *CalculationRequest) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

type CalculationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        float64                `protobuf:"fixed64,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculationResponse) Reset() {
	*x = CalculationResponse{}
	mi := &file_calculator_v1_calculator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculationResponse) ProtoMessage() {}

func (x *CalculationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_v1_calculator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculationResponse.ProtoReflect.Descriptor instead.
func (*CalculationResponse) Descriptor() ([]byte, []int) {
	return file_calculator_v1_calculator_proto_rawDescGZIP(), []int{3}
}

func (x *CalculationResponse) GetResult() float64 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_calculator_v1_calculator_proto protoreflect.FileDescriptor

const file_calculator_v1_calculator_proto_rawDesc = "" +
	"\n" +
	"\x1ecalculator/v1/calculator.proto\x12\rcalculator.v1\x1a\x1bgoogle/protobuf/empty.proto\"\x84\x01\n" +
	"\x16CalculationHistoryItem\x12\x1a\n" +
	"\boperand1\x18\x01 \x01(\x01R\boperand1\x12\x1a\n" +
	"\boperand2\x18\x02 \x01(\x01R\boperand2\x12\x1a\n" +
	"\boperator\x18\x03 \x01(\tR\boperator\x12\x16\n" +
	"\x06result\x18\x04 \x01(\x01R\x06result\"Y\n" +
	"\x1aCalculationHistoryResponse\x12;\n" +
	"\x05items\x18\x01 \x03(\v2%.calculator.v1.CalculationHistoryItemR\x05items\"h\n" +
	"\x12CalculationRequest\x12\x1a\n" +
	"\boperand1\x18\x01 \x01(\x01R\boperand1\x12\x1a\n" +
	"\boperand2\x18\x02 \x01(\x01R\boperand2\x12\x1a\n" +
	"\boperator\x18\x03 \x01(\tR\boperator\"-\n" +
	"\x13CalculationResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x01R\x06result2\xb8\x01\n" +
	"\x11CalculatorService\x12R\n" +
	"\tCalculate\x12!.calculator.v1.CalculationRequest\x1a\".calculator.v1.CalculationResponse\x12O\n" +
	"\n" +
	"GetHistory\x12\x16.google.protobuf.Empty\x1a).calculator.v1.CalculationHistoryResponseB/Z-calculator/backend/pkg/protobuf/calculator/v1b\x06proto3"

var (
	file_calculator_v1_calculator_proto_rawDescOnce sync.Once
	file_calculator_v1_calculator_proto_rawDescData []byte
)

func file_calculator_v1_calculator_proto_rawDescGZIP() []byte {
	file_calculator_v1_calculator_proto_rawDescOnce.Do(func() {
		file_calculator_v1_calculator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_calculator_v1_calculator_proto_rawDesc), len(file_calculator_v1_calculator_proto_rawDesc)))
	})
	return file_calculator_v1_calculator_proto_rawDescData
}

var file_calculator_v1_calculator_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_calculator_v1_calculator_proto_goTypes = []any{
	(*CalculationHistoryItem)(nil),     // 0: calculator.v1.CalculationHistoryItem
	(*CalculationHistoryResponse)(nil), // 1: calculator.v1.CalculationHistoryResponse
	(*CalculationRequest)(nil),         // 2: calculator.v1.CalculationRequest
	(*CalculationResponse)(nil),        // 3: calculator.v1.CalculationResponse
	(*emptypb.Empty)(nil),              // 4: google.protobuf.Empty
}
var file_calculator_v1_calculator_proto_depIdxs = []int32{
	0, // 0: calculator.v1.CalculationHistoryResponse.items:type_name -> calculator.v1.CalculationHistoryItem
	2, // 1: calculator.v1.CalculatorService.Calculate:input_type -> calculator.v1.CalculationRequest
	4, // 2: calculator.v1.CalculatorService.GetHistory:input_type -> google.protobuf.Empty
	3, // 3: calculator.v1.CalculatorService.Calculate:output_type -> calculator.v1.CalculationResponse
	1, // 4: calculator.v1.CalculatorService.GetHistory:output_type -> calculator.v1.CalculationHistoryResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_calculator_v1_calculator_proto_init() }
func file_calculator_v1_calculator_proto_init() {
	if File_calculator_v1_calculator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_calculator_v1_calculator_proto_rawDesc), len(file_calculator_v1_calculator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_calculator_v1_calculator_proto_goTypes,
		DependencyIndexes: file_calculator_v1_calculator_proto_depIdxs,
		MessageInfos:      file_calculator_v1_calculator_proto_msgTypes,
	}.Build()
	File_calculator_v1_calculator_proto = out.File
	file_calculator_v1_calculator_proto_goTypes = nil
	file_calculator_v1_calculator_proto_depIdxs = nil
}
